NumPy 공부해보기

In [ ]:
import numpy as np

NumPy로 1차원 배열 만들기



In [ ]:
a1 = np.array([1, 2, 3, 4, 5]) #1차원 배열 생성
print(a1)
print(type(a1))
print(a1.shape) #ndarray라고 뜨는데 ndarray는 다차원행렬을 뜻한다.
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


NumPy로 2차원 배열만들기


In [ ]:
a2 = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a2)
print(a2.shape)
print(a2[0, 0], a2[1, 1], a2[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


NumPy로 3차원 배열 만들기

In [ ]:
a3 = np.array([ [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
              [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ],
              [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ] ])

print(a3)
print(a3.shape) #(3, 3, 3)이라고 나와있는데 그걸 통해서 배열의 모양을 알 수 있다.

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


- zeoros() : 모든 요소를 0으로 초기화

In [ ]:
np.zeros(10)
#결과 값 : array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

ones(): 모든 요소를 1로 초기화

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- full() : 모든 요소를 지정한 값으로 초기화

In [ ]:
np.full((3, 3), 1.23)

#사용 방식np.full((채워질 요소 부분), 채울 값)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

- eye(): 단위 행렬(identity matrix) 생성
  - 주 대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [ ]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- empty() : 초기화되지 않은 배열 생성
  - 초기화가 없어서 배열 생성비용 저렴하고 빠름
  - 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [ ]:
np.empty(10)
#그 전에 할당된 값들이 따라옴 초기화가 없어서

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

- _like() : 지정된 배열과 shape가 같은 행렬 생성
  - np.zeros_like()
  - np.ones_like()
  - np.full_like()
  - np.empty_like()

In [ ]:
print(a1)
np.zeros_like(a1)

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [ ]:
print(a1)
np.ones_like(a1)

[4 5 6 4 5]


array([1, 1, 1, 1, 1])

In [ ]:
print(a1)
np.full_like(a1, 10)

[4 5 6 4 5]


array([10, 10, 10, 10, 10])

- arange(): 정수 범위로 배열 생성

In [ ]:
np.arange(0, 30, 2) 
# 첫번째 원소: 시작 값
# 두번째 원소: 값의 마지막 값
# 세번째 원소: 증가되는 크기

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

- linspace(): 범위 내에서 균등 간격의 배열 생성

In [ ]:
np.linspace(0, 1, 5)
# 첫번째 원소 : 시작 값
# 두번째 원소 : 값의 마지막 값
# 세번째 원소 : 증가되는 횟수

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- logspace() : 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [ ]:
np.logspace(0.1, 1, 20)
# 첫번째 원소 : 시작 값
# 두번째 원소 : 값의 마지막 값
# 세번째 원소 : log값의 베이스 값

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

# 랜덤값으로 배열 생성


- random.random(): 랜덤한 수의 배열 생성

In [ ]:
np.random.random((3, 3))
#안에 shape모양만 채워주면 알아서 랜덤 값이 채워짐

array([[0.85105391, 0.09741949, 0.38654018],
       [0.77371894, 0.92504342, 0.49377271],
       [0.97639987, 0.90460107, 0.79875396]])

- random.randint() : 일정 구간의 랜덤 정수의 배열 생성

In [ ]:
np.random.normal(0, 1, (3, 3))
# np.random.normal(평균, 표준편차, 배열 모양)

array([[ 1.30875929, -0.98977343,  0.19084161],
       [ 1.3282422 ,  1.04132832, -1.69245484],
       [ 0.51274601, -1.04125588,  0.7493734 ]])

- random.rand() : 균등분포를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.rand(3, 3)
#균등분포란?
#일반적으로 각 이벤트의 결과값을 알 수 없는 경우에 미래에 발생할 이벤트의 결과값 x가 각 예상되는 범위별로 균등한 확류로 일어날 것이라고 예상될 때 사용

array([[0.38287164, 0.43604666, 0.4718741 ],
       [0.83900929, 0.93474363, 0.42434654],
       [0.79488672, 0.8576532 , 0.62718377]])

- random.randn(): 표준 정규 분포를 고려한 랜덤한 수의 배열 생성

In [ ]:
np.random.randn(3, 3)

array([[-1.05757042,  0.95399896,  0.00621745],
       [-0.69629631,  1.30725783, -1.86456152],
       [ 0.20853032,  0.8946995 , -0.72136957]])

# 표준 데이터 타입
```




1.   자료형의 종류
  - 1) 정수형(int : integar)
      - 부호가 있는 정수형 : int8, int16, int32, int64
      - 부호가 없는 정수형 : u
  - 2) 실수형(float)
      - float16, float32, float64
  - 3) 복소수(complex)
      - complex64: 두개의 32비트 부동 소수점으로 표시되는 복소수
      - complex128: 두개의 64비트 부동 소수점으로 표시되는 복소수
  - 4) 부울형(boolean)
    - True, False
2.   데이터 타입을 알기 위한 type(), dtype 속성



In [ ]:
x = np.float32(1.0)
print(x)
print(type(x)) #type()를 이용하여 데이터 타입 알아내기
print(x.dtype) #.dtype를 이용하여 데이터 타입 알아내기

1.0
<class 'numpy.float32'>
float32


In [ ]:
np.zeros(20, dtype=int)
#20개의 숫자를 0으로 만들고 데이터 타입을 int형으로

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3, 3), dtype=bool)
# 3, 3모양으로 다 1로 채움
#1로 채워진 곳은 True로 나타난다

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
np.full((3, 3), 1.0, dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])


# NumPy로 날짜/시간 배열 생성



In [ ]:
date = np.array('2020-01-01', dtype=np.datetime64)
date

array('2020-01-01', dtype='datetime64[D]')

In [ ]:
date + np.arange(12)

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00')
datetime

numpy.datetime64('2020-06-01T12:00')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns')
#ns : 나노초
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

# 배열 조회



In [ ]:
def array_info(array):
  print(array)
  print("ndim: ", array.ndim) #ndim : 배열의 차원 수
  print("shape : ", array.shape) #shape : 배열 각 차원의 크기를 튜플 형태로 표현
  print("dtype : ", array.dtype) #dtype : 데이터 타입
  print("size : ", array.size) #배열 요소의 총 개수를 반환
  print("itemsize:", array.itemsize) #배열 요소의 바이트 크기
  print("nbytes:", array.nbytes) #배열의 전체 요소가 차지하는 바이트 크기
  print("strides:", array.strides) #다음 차원으로 넘어가기 위한 사이즈

인강 다시 봐야함 여기서부터

In [ ]:
array_info(a1)

[4 5 6 4 5]
ndim:  1
shape :  (5,)
dtype :  int64
size :  5
itemsize: 8
nbytes: 40
strides: (8,)


In [ ]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim:  2
shape :  (3, 3)
dtype :  int64
size :  9
itemsize: 8
nbytes: 72
strides: (24, 8)


In [ ]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim:  3
shape :  (3, 3, 3)
dtype :  int64
size :  27
itemsize: 8
nbytes: 216
strides: (72, 24, 8)




# 인덱싱



In [ ]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[4 5 6 4 5]
4
6
5
4


In [ ]:
print(a2)
print(a2[0, 0])
print(a2[0, 2])
print(a2[1, 1])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
9


In [ ]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[2, 2, 2])
print(a3[2, -1, -1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
9


# 슬라이싱




- 슬라이싱 구문:a[start:stop:step]
- 기본 값:start=0, stop=ndim,step=1

In [ ]:
#슬라이싱 : 원하는 부분만 조회
print(a1)
print(a1[0:2]) #0부터 2의 전 부분까지 출력이니까 [4, 5] 출력
print(a1[0:])  #0부터 끝까지 출력
print(a1[:1])  #0부터 1의 전 부분까지 출력이니까 [4] 출력
print(a1[::2]) #step 빼고 아무것도 지정안되어있음 스탭은 2니까 두칸씩 넘어감. 그래서 [4, 6, 5] 출력
print(a1[::-1])#step이 -1이니 출력 형태가 reverse가 되어서 출력

[4 5 6 4 5]
[4 5]
[4 5 6 4 5]
[4]
[4 6 5]
[5 4 6 5 4]


In [ ]:
print(a2)
print(a2[1])
print(a2[1, :])     #start만 적혀있는 걸보니 a2[1] 모든부분만 출력하면 됌
print(a2[:2, :2])   #start말고 stop만 정의되어있음. 그래서 두줄의 배열 0번째랑 1번째 부분만 출력하면 됌
print(a2[1:, ::-1]) #start은 1인데 step은 역순으로 -1 그래서 a2[1]부터 거꾸로 출력
print(a2[::-1, ::-1])#start이랑 step 둘다 -1이여서 완전히 반대로 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]



# 불리언 인덱싱



- 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
- True값인 인덱스의 값만 조회

In [ ]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [True, False, True, True, False]
print(a1[bi])

[4 5 6 4 5]
[5 6 5]
[4 6 4]


In [ ]:
print(a2)
bi = np.random.randint(0, 2, (3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# 팬시 인덱싱(Fancy Indexing)


In [ ]:
print(a2)
row = np.array([0, 2])
col = np.array([1, 2])
print(a2[row, col])
print(a2[row, :])
print(a2[:, col])
print(a2[row, 1])
print(a2[2, col])
print(a2[row, 1:])
print(a2[1:, col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[8 9]
[[2 3]
 [8 9]]
[[5 6]
 [8 9]]



# 배열 값 삽입/수정/삭제/복사









- insert(): 배열의 특정 위치에 값 삽입
- axis를 지정하지 않으면 1차원 배열로 변환
- 추가할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 변환

In [ ]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
c1 = np.insert(a1, 2, 10)
print(c1) 

[4 5 6 4 5]
[10  4  5  6  4  5]
[ 4  5 10  6  4  5]


In [ ]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


- 배열의 인덱싱으로 접근하여 값 수정

In [ ]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1, 3, 4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[4 5 6 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]



# 배열 값 삭제




- delete(): 배열의 특정 위치에 값 삭제
- axis를 지정하지 않으면 1차원 배열로 변환
- 삭제할 방향을 axis로 지정
- 원본 배열 변경없이 새로운 배열 변환

In [ ]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [ ]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)
c2 = np.delete(a2, 1, axis=1)
print(c2)

[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [7 8 3]]
[[1 1]
 [4 6]
 [7 3]]




# 배열 복사



- 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [ ]:
print(a2)
print(a2[:2, :2])
a2_sub = a2[:2, :2]
print(a2_sub)
a2_sub[:, 1] = 0
print(a2_sub)
print(a2)

[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1]
 [4 2]]
[[1 1]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 6]
 [7 8 3]]


- copy(): 배열이나 하위 배열 내의 값을 명시적으로 복사

In [ ]:
print(a2)
a2_sub_copy = a2[:2, :2].copy()
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 0 1]
 [4 0 6]
 [7 8 3]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 6]
 [7 8 3]]



# 배열 전치 및 축 변경


In [ ]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 6]
 [7 8 3]]
[[1 4 7]
 [0 0 8]
 [1 6 3]]


In [ ]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [ ]:
print(a2)
print(a2.swapaxes(1, 0))

[[1 0 1]
 [4 0 6]
 [7 8 3]]
[[1 4 7]
 [0 0 8]
 [1 6 3]]


In [ ]:
print(a3)
print(a3.swapaxes(0, 1))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]




# 배열 재구조화



- reshape(): 배열의 형상을 변경

In [ ]:
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]



# 배열 크기 변경


- 배열 모양만 변경

In [ ]:
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5, 2))
print(n2)

[[2 9 2 3 8]
 [8 1 6 9 3]]
[[2 9]
 [2 3]
 [8 8]
 [1 6]
 [9 3]]


- 배열 크기 증가
- 남은 공간은 0으로 채워짐


# 배열 추가



- append(): 배열의 끝에 값 추가

- axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [ ]:
c2 = np.append(a2, b2)
print(c2)

[1 0 1 4 0 6 7 8 3 1 1 1 7 8 3]




# 배열 연결



- concatenate(): 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [ ]:
a1 = np.array([1, 3, 5])
b1 = np.array([2, 4, 6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [ ]:
c1 = np.array([7, 8, 9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [ ]:
a2 = np.array([[1, 2, 3], 
               [4, 5, 6]])
np.concatenate([a2, a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- vstack(): 수직스택, 1차원으로 연결

In [ ]:
np.vstack([a2, a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

- hstack([a2, a2]): 수평 스택, 2차원으로 연결

In [ ]:
np.hstack([a2, a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- dstack(): 깊이 스택, 3차원으로 연결

In [ ]:
np.dstack([a2, a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

- stack(): 새로운 차원으로 연결

In [ ]:
np.stack([a2, a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])


# 배열 분할



- split():배열 분할

In [ ]:
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])
print(b1, c1)
b1, c1, d1, e1, f1 = np.split(a1, [2, 4, 6, 8])
print(b1, c1, d1, e1, f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


- vsplit(): 수직 분할, 1차원으로 분할

In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


- hsplit(): 수평 분할, 2차원으로 분할

In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


- dsplit(): 깊이 분할, 3차원으로 분할

In [ ]:
a2 = np.arange(1, 28).reshape(3, 3, 3)
print(a3)
b3, c3 = np.vsplit(a3, [2])
print(b3)
print(c3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]



# 배열 연산


- NumpPy의 배열 연산은 벡터화 연산을 사용
- 일반적으로 NumPy의 범용 함수를 통해 구현
- 배열 요소에 대한 반복적인 계산을 효율적으로 수행


# 브로드캐스팅


In [ ]:
a1 = np.array([1, 2, 3])
print(a1)
print(a1 + 5)

a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(a1 + a2)

b2 = np.array([1, 2, 3]).reshape(3, 1)
print(b2)
print(a1 + b2)

[1 2 3]
[6 7 8]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]



# 산술 연산


In [ ]:
a1 = np.arange(1, 10)
print(a1)
b1 = np.random.randint(1, 10, size=9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1 // b1)
print(a1 ** b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[9 6 2 6 5 5 5 5 9]
[10  8  5 10 10 11 12 13 18]
[-8 -4  1 -2  0  1  2  3  0]
[ 9 12  6 24 25 30 35 40 81]
[0.11111111 0.33333333 1.5        0.66666667 1.         1.2
 1.4        1.6        1.        ]
[0 0 1 0 1 1 1 1 1]
[        1        64         9      4096      3125      7776     16807
     32768 387420489]
[1 2 1 4 0 1 2 3 0]


In [ ]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.random.randint(1, 10, size=(3, 3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[6 1 3]
 [4 3 8]
 [2 2 5]]
[[ 7  3  6]
 [ 8  8 14]
 [ 9 10 14]]
[[-5  1  0]
 [ 0  2 -2]
 [ 5  6  4]]
[[ 6  2  9]
 [16 15 48]
 [14 16 45]]
[[0.16666667 2.         1.        ]
 [1.         1.66666667 0.75      ]
 [3.5        4.         1.8       ]]
[[0 2 1]
 [1 1 0]
 [3 4 1]]
[[      1       2      27]
 [    256     125 1679616]
 [     49      64   59049]]
[[1 0 0]
 [0 2 6]
 [1 0 4]]



# 절대값 함수


- absolute(), abs(): 내장된 절대값 함수

In [ ]:
a1 = np.random.randint(-10, 10, size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[ 1  5  4 -3  5]
[1 5 4 3 5]
[1 5 4 3 5]



# 제곱/제곱급 함수


- square, sqrt: 제곱, 제곱근 함수

In [ ]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[ 1  5  4 -3  5]
[ 1 25 16  9 25]
[1.         2.23606798 2.                nan 2.23606798]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until



# 지수와 로그 함수

In [ ]:
a1 = np.random.randint(1, 10, size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1, 2))

[9 1 9 9 1]
[8.10308393e+03 2.71828183e+00 8.10308393e+03 8.10308393e+03
 2.71828183e+00]
[512.   2. 512. 512.   2.]
[81  1 81 81  1]


In [ ]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[9 1 9 9 1]
[2.19722458 0.         2.19722458 2.19722458 0.        ]
[3.169925 0.       3.169925 3.169925 0.      ]
[0.95424251 0.         0.95424251 0.95424251 0.        ]



# 집계 함수


- cumsum(): 누적합 계산

In [ ]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0))
print(np.cumsum(a2, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


- diff(): 차분 계산

In [ ]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))
print(np.diff(a2, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1]
 [1 1]
 [1 1]]
[[3 3 3]
 [3 3 3]]
[[3 3 3]
 [3 3 3]]


- prod(): 곱 계산

In [ ]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0))
print(np.prod(a2, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
362880
[ 28  80 162]
[ 28  80 162]


- cumprod(): 누적곱 계산


In [ ]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0))
print(np.cumprod(a2, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[     1      2      6     24    120    720   5040  40320 362880]
[[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]
[[  1   2   3]
 [  4  10  18]
 [ 28  80 162]]


- dot()/matmul():점곱/행렬곱계산

In [ ]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2, b2))
print(np.matmul(a2, b2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 6  6  6]
 [15 15 15]
 [24 24 24]]
[[ 6  6  6]
 [15 15 15]
 [24 24 24]]


- tensordot(): 텐서곱 계산

In [ ]:
print(a2)
print(b2)
print(np.tensordot(a2, b2))
print(np.tensordot(a2, b2, axes = 0))
print(np.tensordot(a2, b2, axes = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
45
[[[[1 1 1]
   [1 1 1]
   [1 1 1]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]]]
[[ 6  6  6]
 [15 15 15]
 [24 24 24]]


- cross(): 벡터곱

In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]
print(np.cross(x, y))

[-3  6 -3]


- inner()/outer(): 내적/외적

In [ ]:
print(a2)
print(b2)
print(np.inner(a2, b2))
print(np.outer(a2, b2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 6  6  6]
 [15 15 15]
 [24 24 24]]
[[1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9]]


- mean(): 평균 계산

In [ ]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
[4. 5. 6.]
[2. 5. 8.]


- std(): 표준 편차 계산

In [ ]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2.581988897471611
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


var(): 분산 계산

In [ ]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis=0))
print(np.var(a2, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6.666666666666667
[6. 6. 6.]
[0.66666667 0.66666667 0.66666667]


- min(): 최소값

In [ ]:
print(a2)
print(np.min(a2))
print(np.min(a2, axis=0))
print(np.min(a2, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[1 2 3]
[1 4 7]


- max(): 최대값

In [ ]:
print(a2)
print(np.max(a2))
print(np.max(a2, axis=0))
print(np.max(a2, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[7 8 9]
[3 6 9]


- argmin():최소값 인덱스

In [ ]:
print(a2)
print(np.argmin(a2))
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0
[0 0 0]
[0 0 0]


- argmax(): 최대값 인덱스

In [ ]:
print(a2)
print(np.argmax(a2))
print(np.argmax(a2, axis=0))
print(np.argmax(a2, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
[2 2 2]
[2 2 2]


- median(): 중앙값

In [ ]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis=0))
print(np.median(a2, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
[4. 5. 6.]
[2. 5. 8.]


- percentile(): 백분위 수

In [ ]:
a1 = np.array([0, 1, 2, 3])
print(a1)
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print(np.percentile(a1, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


- any()

In [ ]:
a2 = np.array([[False, False, False],
               [False, True, True],
               [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


- all()

In [ ]:
a2 = np.array([[False, False, False],
               [False, True, True],
               [False, True, True]])
print(a2)
print(np.all(a2))
print(np.all(a2, axis=0))
print(np.all(a2, axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
False
[False False False]
[False False False]



# 비교 연산

In [ ]:
  a1 = np.arange(1, 10)
  print(a1)
  print(a1 == 5)
  print(a1 != 5)
  print(a1 < 5)
  print(a1 <= 5)
  print(a1 > 5)
  print(a1 >= 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]



# 배열 정렬



In [ ]:
a1 = np.random.randint(1, 10, size = 10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)
print(a1.sort())
print(a1)

[6 3 8 1 7 7 3 9 2 5]
[1 2 3 3 5 6 7 7 8 9]
[6 3 8 1 7 7 3 9 2 5]
[3 8 1 6 9 0 4 5 2 7]
[6 3 8 1 7 7 3 9 2 5]
None
[1 2 3 3 5 6 7 7 8 9]



# 부분 정렬



- partition(): 배열에서 k개의 작은 값을 반환

In [ ]:
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1, 3))

[2 9 4 5 1 7 5 2 9 3]
[2 1 2 3 4 5 9 7 9 5]


In [ ]:
a2 = np.random.randint(1, 10, size=(5,5))
print(a2)
print(np.partition(a2, 3))
print(np.partition(a2, 3, axis=0))
print(np.partition(a2, 3, axis=1))

[[6 8 8 5 8]
 [6 1 1 5 8]
 [9 9 9 5 3]
 [5 3 1 9 6]
 [9 3 7 1 9]]
[[5 6 8 8 8]
 [5 1 1 6 8]
 [5 3 9 9 9]
 [3 1 5 6 9]
 [1 7 3 9 9]]
[[5 3 1 1 6]
 [6 3 7 5 3]
 [6 1 1 5 8]
 [9 8 8 5 8]
 [9 9 9 9 9]]
[[5 6 8 8 8]
 [5 1 1 6 8]
 [5 3 9 9 9]
 [3 1 5 6 9]
 [1 7 3 9 9]]



# 배열 입출력



In [ ]:
a2 = np.random.randint(1, 10, size=(5,5))
print(a2)
np.save("a", a2)

[[3 4 8 8 4]
 [8 7 6 6 4]
 [2 6 8 1 8]
 [6 2 8 4 6]
 [2 6 3 1 7]]


In [ ]:
b2 = np.random.randint(1, 10, size=(5, 5))
print(b2)
np.savez("ab", a2, b2)

[[6 9 7 4 1]
 [5 2 8 6 8]
 [1 1 1 8 5]
 [8 2 2 9 1]
 [7 4 2 1 5]]


In [ ]:
!ls

ab.npz	a.npy  sample_data


In [ ]:
npy = np.load("a.npy")
print(npy)

[[3 4 8 8 4]
 [8 7 6 6 4]
 [2 6 8 1 8]
 [6 2 8 4 6]
 [2 6 3 1 7]]


In [ ]:
print(a2)
np.savetxt("a.csv", a2, delimiter=',')

[[3 4 8 8 4]
 [8 7 6 6 4]
 [2 6 8 1 8]
 [6 2 8 4 6]
 [2 6 3 1 7]]


!ls

In [ ]:
!cat a.csv

3.000000000000000000e+00,4.000000000000000000e+00,8.000000000000000000e+00,8.000000000000000000e+00,4.000000000000000000e+00
8.000000000000000000e+00,7.000000000000000000e+00,6.000000000000000000e+00,6.000000000000000000e+00,4.000000000000000000e+00
2.000000000000000000e+00,6.000000000000000000e+00,8.000000000000000000e+00,1.000000000000000000e+00,8.000000000000000000e+00
6.000000000000000000e+00,2.000000000000000000e+00,8.000000000000000000e+00,4.000000000000000000e+00,6.000000000000000000e+00
2.000000000000000000e+00,6.000000000000000000e+00,3.000000000000000000e+00,1.000000000000000000e+00,7.000000000000000000e+00


In [ ]:
csv = np.loadtxt("a.csv", delimiter=',')
print(csv)

[[3. 4. 8. 8. 4.]
 [8. 7. 6. 6. 4.]
 [2. 6. 8. 1. 8.]
 [6. 2. 8. 4. 6.]
 [2. 6. 3. 1. 7.]]


In [ ]:
print(b2)
np.savetxt("b.csv", b2, delimiter=',', fmt='%.2e', header='c1, c2, c3, c4, c5')

[[6 9 7 4 1]
 [5 2 8 6 8]
 [1 1 1 8 5]
 [8 2 2 9 1]
 [7 4 2 1 5]]


In [ ]:
!cat b.csv

# c1, c2, c3, c4, c5
6.00e+00,9.00e+00,7.00e+00,4.00e+00,1.00e+00
5.00e+00,2.00e+00,8.00e+00,6.00e+00,8.00e+00
1.00e+00,1.00e+00,1.00e+00,8.00e+00,5.00e+00
8.00e+00,2.00e+00,2.00e+00,9.00e+00,1.00e+00
7.00e+00,4.00e+00,2.00e+00,1.00e+00,5.00e+00


In [ ]:
csv = np.loadtxt("b.csv", delimiter=',')
print(csv)

[[6. 9. 7. 4. 1.]
 [5. 2. 8. 6. 8.]
 [1. 1. 1. 8. 5.]
 [8. 2. 2. 9. 1.]
 [7. 4. 2. 1. 5.]]
